### ISSUE TITLE
event-set for arbitrary functions?

### ISSUE THREAD

**Issue by beccannlittle** [ngokevin/kframe#33]
I'd like to assign arbitrary functions to events on entities, so I did this:

```html
<a-entity event-set-function="evnt:click;fcn:logger"></a-entity>
```
```js
AFRAME.registerComponent('event-set-function', {
  schema: {
    evnt: {type: 'string', default: ''},
    fcn: {type: 'string', default: ''}
  },
  init: function() {
    var evnt = this.data.evnt
    var fcn = this.data.fcn
    this.el.addEventListener(evnt, function() {
      if(window[fcn]) {
        window[fcn]()
      }
    })
  }
})

var logger = function() {
  console.log('It works!')
}
```
I'd like to know whether this is too naive of an approach or if I'm thinking of this the wrong way before I make a PR on the `event-set` component.

**Comment by ngokevin** [comment]
Thanks for the suggestion. The best way is you should write a component specifically for your function rather than trying to make a generic function caller. 

```
AFRAME.registerComponent('do-this', {
  schema: {
    evt: {default: 'click'}
  }
});
```

Though if you want, you could try to implement a component that calls from a set of registered functions. That'd be interesting. But it'd be out of scope of this small component.
