### ISSUE TITLE
Change animation component API

### ISSUE THREAD

**Issue by Tiagojdferreira** [ngokevin/kframe#53]
I just recently started using aframe and I tried the [tutorial](https://aframe.io/docs/0.5.0/guides/#adding-animation) using your animation instead of the native `<a-animation>` component. It was not that hard to accomplish, but some changes in the interface could make portability much easier.

Is there any specific reason why you use `dir, property, loop` instead of `direction, attribute, repeat` ? If not I would be happy to make a PR proposing changes

**Comment by ngokevin** [comment]
It's just a different API, the `<a-animation>` is not standard by any means, and I want to port this component to replace `<a-animation>` at some point.

`dir` to be shorter and it's what `anime` uses
`property` because they interpolate component properties, not attributes
`loop` because `loop: true` is easier than `repeat: indefinite`
`repeat` is also a separate property

**Comment by Tiagojdferreira** [comment]
Thanks for the explanation :+1:
